import { IGRPMenuProps } from '@/features/menus/types';

export const IGRP_DEFAULT_MENU: IGRPMenuProps[] = [

  {
    id: 7,
    name: 'Licenças',
    type: 'MENU_PAGE',
    position: 1,
    icon: 'Logs',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/license',
    parentId: null,
    applicationId: 1,
    resourceId: null,
    createdBy: 'admin',
    createdDate: '2022-01-01T12:00:00.000Z',
    lastModifiedBy: 'admin',
    lastModifiedDate: '2022-01-01T12:00:00.000Z',
  },
  {
    id: 12,
    name: 'Configurações',
    type: 'MENU_PAGE',
    position: 1,
    icon: 'Settings2',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '',
    parentId: null,
    applicationId: 1,
    resourceId: null,
    createdBy: 'admin',
    createdDate: '2022-01-01T12:00:00.000Z',
    lastModifiedBy: 'admin',
    lastModifiedDate: '2022-01-01T12:00:00.000Z',
  },
  {
    id: 9,
    name: 'Tipos de Estabelecimento',
    type: 'MENU_PAGE',
    position: 1,
    icon: '',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/establishment',
    parentId: 12,
    applicationId: 1,
    resourceId: null,
    createdBy: 'admin',
    createdDate: '2022-01-01T12:00:00.000Z',
    lastModifiedBy: 'admin',
    lastModifiedDate: '2022-01-01T12:00:00.000Z',
  },
  {
    id: 6,
    name: 'Classes',
    type: 'MENU_PAGE',
    position: 1,
    icon: '',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/classes',
    parentId: 12,
    applicationId: 1,
    resourceId: null,
    createdBy: 'admin',
    createdDate: '2022-01-01T12:00:00.000Z',
    lastModifiedBy: 'admin',
    lastModifiedDate: '2022-01-01T12:00:00.000Z',
  },

  {
    id: 4,
    name: 'Actividades',
    type: 'MENU_PAGE',
    position: 1,
    icon: '',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/activities',
    parentId: 12,
    applicationId: 1,
    resourceId: null,
    createdBy: 'admin',
    createdDate: '2022-01-01T12:00:00.000Z',
    lastModifiedBy: 'admin',
    lastModifiedDate: '2022-01-01T12:00:00.000Z',
  },
];
